[package]
name = "basalt-node"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "1"

basalt = {path = "../"}

[build-dependencies]
napi-build = "1"
